// Users
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const PLAYER_PROFILE_SUCCESS = 'PLAYER_PROFILE_SUCCESS';
export const POST_ASSOC_STORE_PLAYER_SUCCESS = 'POST_ASSOC_STORE_PLAYER_SUCCESS';
export const POST_REMOVE_STORE_PLAYER_SUCCESS = 'POST_REMOVE_STORE_PLAYER_SUCCESS';
export const POST_SAVE_PLAYER_SUCCESS = 'POST_SAVE_PLAYER_SUCCESS';

export const POST_ERROR = 'POST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR'; //ensures that the error state is reset after successfully completing an action



export const SAVE_GAME_SUCCESS = 'SAVE_GAME_SUCCESS';



export const GET_SHOPS_SUCCESS = 'GET_SHOPS_SUCCESS';
export const DELETE_SHOP_SUCCESS = 'DELETE_SHOP_SUCCESS';
export const SHOP_PROFILE_SUCCESS = 'SHOP_PROFILE_SUCCESS';



// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
